name: curve_explorer
description: A visual explorer for Flutter animation curves.

version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  scoped_model: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: FiraCode
      fonts:
        - asset: fonts/FiraCode-Regular.ttf
          style: normal
    - family: FiraCodeBold
      fonts:
        - asset: fonts/FiraCode-Bold.ttf
          style: normal
    - family: FiraCodeLight
      fonts:
        - asset: fonts/FiraCode-Light.ttf
          style: normal
    - family: FiraCodeMedium
      fonts:
        - asset: fonts/FiraCode-Medium.ttf
          style: normal
