name: curve_explorer
description: A visual explorer for Flutter animation curves.

version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  scoped_model: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
